### PR TITLE
xpdconf v0.4.5

### PR DESCRIPTION
**Pull request by nsls2forge**
It is very likely that the current package version for this feedstock is out of date.
Notes for merging this PR:
1. Feel free to push to the bot's branch to update this PR if needed.
2. The bot will almost always only open one PR per version.
Checklist before merging this PR:
- [ ] Dependencies have been updated if changed
- [ ] Tests have passed 
- [ ] Updated license if changed and `license_file` is packaged 

Note that the bot will stop issuing PRs if more than 3 Version bump PRs generated by the bot are open. If you don't want to package a particular version please close the PR.

Here is a list of all the pending dependencies (and their versions) for this repo. The first package is the current feedstock package. Please double check all dependencies before merging.

# Feedstock Packages Build Status

| # | Repo | Build <br/> Health | nsls2forge <br/> PyPI <br/> defaults <br/> conda-forge <br/> GitHub <br/> Versions | Downloads|
|:---:|:-------:|:-----------:|:---------------:|:--------------:|
|1|[xpdconf](https://github.com/nsls-ii-forge/xpdconf-feedstock)|[Build Status](https://dev.azure.com/nsls2forge/nsls2forge/_build) <br/> [Code Health](https://landscape.io/github/nsls-ii-forge/xpdconf-feedstock/master)|[nsls2forge version](https://anaconda.org/nsls2forge/xpdconf) <br/> [PyPI version](https://pypi.org/project/xpdconf/) <br/> [defaults version](https://anaconda.org/anaconda/xpdconf) <br/> [conda-forge version](https://anaconda.org/conda-forge/xpdconf) <br/> [GitHub version](https://github.com//xpdconf)|[Downloads](https://anaconda.org/nsls2forge/xpdconf)|

Closes #4.

### CODE REVIEW

**Comment by st3107** [comment]
Update the .gz files. Re-run the CI.

**Comment by mrakitin** [comment]
I think it needs a new release so that the archives are correct on both PyPI and GitHub. I did notice that https://github.com/xpdAcq/xpdConf/archive/0.4.3.tar.gz was updated, but not the uploaded artifact https://github.com/xpdAcq/xpdConf/releases/download/0.4.3/xpdconf-0.4.3.tar.gz.

**Comment by st3107** [comment]
Got it. I will make it a new release.

**Comment by mrakitin** [comment]
Thank you, I appreciate your help with that.

**Comment by mrakitin** [comment]
@st3107, for some reason, the file uploaded to https://pypi.org/project/xpdconf/0.4.4/#files still has the name `xpdConf`. It should not happen with `python setup.py sdist` anymore. Was everything cleaned up before rerunning the build locally?

**Comment by st3107** [comment]
I tried locally with ``python setup.py sdist``. It is still xpdConf. I need to figure out where is capitalized word is coming from.

**Comment by st3107** [comment]
I fixed the name. I forgot to delete the old egg-info before I distributed the package locally.

**Comment by st3107** [comment]
Ready to merge

**Comment by mrakitin** [comment]
> I fixed the name. I forgot to delete the old egg-info before I distributed the package locally.

Great find. I always execute step number 11 from https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-releases.html (`git clean -dfx`) to avoid such issues, that's why I asked.

**Review by mrakitin — APPROVED** [review]

**Comment by mrakitin** [comment]
@st3107, please note a test https://github.com/nsls-ii-forge/xpdconf-feedstock/pull/5/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR31-R32 for the `example/*.yaml` files. If it is ever broken in the future, we will notice that.

I'll try to add more tests to have a better coverage. Please do not merge yet.

**Comment by mrakitin** [comment]
@st3107, I added the `pytest` tests from the package here, so it's even more reliable. Basically, we may not need another explicit/inline test that uses the same `pkg_resources` approach, but I'd like to keep it here in case the suite of tests changes in the package. Feel free to merge.

**Comment by mrakitin** [comment]
Going to self-merge to unblock CI testing of the `profile_collection`.

**Pull request merged**
